name: Run tests

on:
  push:

env:
  TESTS_PATH: './ScambiciAPI/tests/Scambici.Tests/'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - name: 'Setup DotNet Environment'
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: '3.1.100'
      - name: 'Run Tests'
        run: |
          pushd './${{ env.TESTS_PATH }}'
          dotnet test
          popd

